spring:
  application:
    name: mumumall

  # 默认 dev 环境
  profiles:
    active: prod

  # 支持 swagger
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  # 设置上传文件大小
  servlet:
    multipart.max-file-size: 100MB
    multipart.max-request-size: 100MB

  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss

  # 数据源
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://huazll5510.mysql.rds.aliyuncs.com:3306/qf_mall
    username: huauz
    password: Huauz125510

  # Redis缓存配置
  redis:
    host: 127.0.0.1
    port: 6379
    #    password:
    timeout: 5000
    database: 0

  # 邮件服务器配置
  mail:
    # SMTP
    host: smtp.qq.com
    # 邮箱
    username: mail_notice@foxmail.com
    # 密码
    password: bxjmyxtwwuccjhba
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
            port: 465
# 上传文件配置
web:
  # 上传路径
  upload-path: E:\img
  # 上传IP+端口
  uri: 127.0.0.1:8080

server:
  port: 8080
  servlet:
    # session 失效时间 1 天
    session:
      timeout: 86400
    context-path: /api

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值（默认为 1）
      logic-not-delete-value: 0 # 逻辑未删除值（默认为 0）
    banner: false # 取消Logo
