
# 生产环境配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/qf_mall
    username: admin
    password: 123456

  # Redis缓存配置
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 5000
    database: 0

  # 设置上传文件大小
  servlet:
    multipart.max-file-size: 100MB
    multipart.max-request-size: 100MB

  # 邮件服务器配置
  mail:
    # SMTP
    host: smtp.qq.com
    # 邮箱
    username: 
    # 密码
    password: 
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
            port: 465

  # 上传文件配置
web:
  # 上传路径
  upload-path: 
  # 上传IP+端口
  uri: 127.0.0.1:5523
